### ISSUE TITLE
Proble with the Cessna Citation CJ4 FMS MCDU Overlay

### ISSUE THREAD

**Issue by clop6719** [Simstrumentation/Air-Manager#8]
Hi:

I've been trying to test the Cessna Citation CJ4 FMS MCDU Overlay. All the buttons work properly but the CJ4_FMC_1_BTN_LX (X=1..6) and CJ4_FMC_1_BTN_RX (X=1..6) don't seem to work.

Hope you can help me with this

Thahks for your excelent work
Charles

**Comment by rob2791** [comment]
Make sure you have version 2.0 (released 9-26-2021) of the FMS.
Try restarting Air Manager or your SIM, and/or your entire computer. :-)
There might be a bug with Air Manager trying to push the latest MSFS2020 plugin that makes some things act funny. 

I just tested it and it's working for me. I'm running AM 4.0.2.
Let me know if you still have issues.

**Comment by clop6719** [comment]
Hi Rob:

Thanks. It really helped me your input. The only discrepancy I had was the Air manager plugin ... I was using the 3.6. I updated to the latest (3.7) and now is working perfectly.

I don't want to bother you but I'm trying to reuse your code for the Aerosoft CRJ airplane for MSFS. So far, I changed only the name of the LVAR's of the FMC and with that small change it didn't work. Do you have any suggestion that can help me?

Again ...thanks for your help and patience!!

Charles

**Comment by ToddLorey** [comment]
Hi there,
I'll hazard a guess here on the FMC commands not working for the CRJ.  I looked through the Hubhop list and don't see any commands for the CRJ's FMC.   Maybe they don't exist yet?  Where did you find the LVARs?  I'm flying a bit blind here because I don't have the CRJ.   It's also possible that you have a syntax error somewhere.  Very easy to miss a comma, closed quote or parenthesis.  Does the instrument load without errors if you click the "RUN" at the top of the edit page?

Another possibility is that you may need to use the "Mobiflight." prefix.  For example, send fs2020_event("Mobiflight.ASCRJ_FCP_HDG_SEL_INC").  Or you can try adding an H: instead of the Mobiflight.  

Still another possibility is that they are truly LVARs instead of events, so you'd need to use the fs2020_variable_write command instead of the event trigger.  And remember that a variable needs a type as well, so it might be something like this:  fs2020_variable_write("L:ASCRJ_FUEL_PUMP_L", "Bool", true).

**Comment by clop6719** [comment]
Hi there:

You're such a crack!!. It really helped me out...Now is working on the CRJ....with this:

---------------
function FMC_1_BTN_L1()
   fs2020_variable_write("L:ASCRJ_MCDU1_LSK1L","INT",1)
   sound_play(snd_click)
end
-----------------

BTW...I got the LVARS from a chat in AS site...just in case you're interested

Again....Thanks very much ;-)

Charles

**Comment by clop6719** [comment]
Hi there:

I'm here again...I'm having an issue with the CRJ FMS. Sorry to bother you again .. The thing is that I'm getting repeated values of the same key. For example if I'm pushing the A keypad I may get one and sometimes two AA...It's happening with most of the keys. Do you have any clue of what's going on here?

All the best
